### ISSUE TITLE
Cannot build bignum on El Capitan

### ISSUE THREAD

**Issue by phenaproxima** [justmoon/node-bignum#69]
I don't speak C++ so I have no idea what's going on here, but I get a lot of "undefined"-type errors when trying to build Bignum.

[npm-debug.txt](https://github.com/justmoon/node-bignum/files/34728/npm-debug.txt)

**Comment by Giancarlo1974** [comment]
I realized that the real problem lies in node gyp
The core of the problem is that node-gyp is no longer being actively developed

This is the best guide I've found:

https://www.robertkehoe.com/2015/03/fix-node-gyp-rebuild-error-on-windows/

But not, however, resolve the problem
Unfortunately too many modules use node-gyp

**Comment by rvagg** [comment]
node-gyp is being actively developed, it's now part of the Node.js Foundation GitHub org @ https://github.com/nodejs/node-gyp, it's just that compiling anything on Windows is a rough game and you need just the right versions of everything to make it work. See the node-gyp docs to get the versions right.

**Comment by rvagg** [comment]
Sorry, OP mentioned El Capitan, follow-up mentioned Windows.

Re El Capitain, is it possible you don't have the xcode command line tools installed? The log you pointed to doesn't have anything useful re node-gyp. See http://railsapps.github.io/xcode-command-line-tools.html for some instructions on commandline tools.
