### ISSUE TITLE
Node Depency Issue

### ISSUE THREAD

**Issue by xanatas** [justmoon/node-bignum#79]
With the new release my system errors:  {"node":">=0.12"} (current: {"node":"0.10.40","npm":"1.4.28"})
But just since today so maybe this is not intended or it really does not work with node 0.10.40?

I just include Bignum with another depency from another package with "bignum": ">=0.6.1". so i cannot change it easily.

Maybe its something you could consider fixing...if possible.

**Comment by tracker1** [comment]
Node 0.10 is *really* old at this point, and 0.12 didn't have many breaking changes... can't you just test your app(s) with 0.12?

**Comment by rvagg** [comment]
where are you getting `{"node":">=0.12"}` from? there _was_ a `>=0.8` in bignum but I removed the restriction entirely. Perhaps this is coming from another dependency somewhere? bignum should be perfectly happy with v0.10 and I regularly test with it too.

Also, you may want to consider upgrading your version of Node to at least the latest v0.10 release, particularly since you have an obsolete version of npm there, you should be on npm >= v2 at least.

**Comment by xanatas** [comment]
Im developing with the Meteor framework and its apparently not 0.12 ready.
I fixed the dependency and include and old version of bignum now but if i include the latest versions i get the error... maybe there is another dependency the log doesnt show me...

**Comment by rvagg** [comment]
linux? windows? osx? can you give some log output?

**Comment by xanatas** [comment]
I fixed all dependecies i had to fork them all and did it myself. its this node 0.10 thing. Meteor Group is working on a node update on the next release.
